# config.yaml
model:
  name: "microsoft/DialoGPT-small"
  max_length: 512
  temperature: 0.7

training:
  epochs: 3
  batch_size: 4
  learning_rate: 5e-5
  train_split: 0.8

data:
  path: "data/raw/womenchatbot.csv"
  text_columns:
    question: "question"
    answer: "answer"

paths:
  model_output: "models/fine_tuned"
  logs: "logs/"